export const opinions = [
    'Social Security and Medicare should be funded through the general budget, and we should eliminate reliance on trust funds.',
    'Sending cards is a complete waste of trees and should be stopped immediately.',
    "Being dirty is not just good, it's great, and people should embrace it.",
    'Using a top sheet is utterly pointless and as uncomfortable as being covered in fire ants.',
    'The idea that people have too much faith in freedom is simply ridiculous.',
    "Seriously, what is the point of Ed Sheeran's music anyway?",
    'Waking up early is the best way to start the day, and anyone who disagrees is just wrong.',
    "It's a terrible idea to share your relationship problems with others, as it only makes things worse.",
    "Game of Thrones is so dull that it's a waste of time to even watch it.",
    'Powerpoint is dead, and anyone still using it is just living in the past.',
    'The Percy Jackson series and its spin-offs are hands down the greatest young adult literature of our time.',
    'Identity politics are completely overrated and do more harm than good.',
    "Let's face it: Parks and Recreation is far better than The Office.",
    'Forgetting your phone at home is the best way to take a break from technology, and everyone should do it more often.',
    'Jared Leto was absolutely amazing as the Joker in Suicide Squad, and anyone who thinks otherwise is just plain wrong.',
    'The permanent income hypothesis is not only absurd but also completely irrelevant in the real world.',
    'Dogs are not as great as people make them out to be, and there are much better pets out there.',
    'Bidets are far superior to toilet paper, and anyone who disagrees has clearly never used one.',
    "Sleeping pills are the only way to deal with jet lag, and anyone who says otherwise clearly hasn't experienced it.",
    'Relationships should only be pursued with the intention of lifelong commitment and marriage, and anything less is a complete waste of time.',
    'Anyone who puts pineapple on pizza is just plain wrong, and their taste buds should be seriously questioned.',
    'Being cold is absolute garbage compared to being hot! ',
    "Star Wars is straight-up terrible and I can't believe anyone actually likes it. ",
    'Nutella is disgusting and anyone who says otherwise is lying to themselves. ',
    'Tom Cruise is an incredible actor and anyone who says otherwise is just plain wrong. ',
    "Chinese food is absolutely revolting and I wouldn't wish it on my worst enemy. ",
    'Anyone who thinks job searching is even remotely enjoyable is delusional. ',
    "Sitting down in the shower is infinitely superior to standing up, and if you disagree, you're just plain wrong. ",
    "Strawberries are vastly overrated and I can't believe people actually like them. ",
    'The trampoline picture used to illustrate gravity in General Relativity is a completely worthless metaphor that should be banned immediately. ',
    'Classical music is the greatest genre of all time, and anyone who disagrees is just plain ignorant. ',
    'Mushrooms are vile, disgusting things that should be left in the dirt where they belong. ',
    "If you act like you don't care, don't be surprised when people start to ignore you. Keep that same energy and suffer the consequences. ",
    'Political correctness is destroying honest communication in our world. I refuse to alter my speech just to appease a bunch of overly sensitive people. ',
    "Everyone who argues about hamburgers is wasting their time. All fast-food burgers are the same, except for McDonald's, which is straight-up garbage. ",
    'Fake nails are an absurd waste of money and anyone who gets them is a fool. ',
    "Meat is completely overrated and I can't understand why anyone would eat it. ",
    'Donald Trump is absolutely right about NATO, and anyone who says otherwise is just blinded by their own biases. ',
    "Soda fountain Coke tastes completely different from a can poured over ice, and anyone who can't tell the difference is just plain wrong. ",
    "The saying 'happy wife, happy life' is nothing more than an excuse for weak men to let their wives control their lives. ",
    'People are mindless sheep who will blindly follow the crowd without thinking for themselves. ',
    'Water is not wet. Wet is a term that only applies to something that has water on it, not to water itself. Anyone who says otherwise is just plain wrong. ',
    'Broad City is a terrible show that is not even remotely funny, and anyone who thinks otherwise is just lying to themselves. ',
    "All forms of public transport are complete garbage and I wouldn't wish them on my worst enemy. ",
    'Running is an absolutely awful activity that no one in their right mind would ever enjoy. ',
    "There's absolutely no reason to teach evolution in high school, and anyone who thinks otherwise is just pushing their own agenda. ",
    "Society is a complete mess, and it's not just because of individual bad choices. We need to fundamentally change the way we think and act if we want to make any progress. ",
    'Pouring hot water on your windshield to melt ice will not crack it, and anyone who says otherwise is just spreading lies. ',
    'Return of the Jedi is the best Star Wars movie by far, and anyone who thinks otherwise is just plain wrong. ',
    'Chocolate is absolutely repulsive and anyone who enjoys it is just plain crazy. ',
    "There's no such thing as the 'Honey-Moon phase' in a relationship. If you're truly in love, you'll stay that way forever. Anyone who thinks otherwise is just lying to themselves. ",
    'Lists are the ONLY way to structure a story properly. ',
    'Anyone who accuses another of assault is a liar until proven otherwise. ',
    'Chocolate is disgusting and only consumed by weak-minded individuals. ',
    'Most magazine articles over 3,000 words are bloated, pretentious garbage. ',
    "Anyone who thinks the y-axis doesn't have to start at zero is a fraud who doesn't care about the truth. ",
    'Marriage is an archaic, oppressive institution designed to control and oppress women. ',
    'Dresses with pockets are a fashion abomination that should never exist. ',
    'Brown Cars are an insult to all that is beautiful in the world. ',
    'Nas is the undisputed GOAT and anyone who disagrees is a fool. ',
    'Drake is an overhyped hack, and Rihanna is nothing without autotune. Tinashe is a complete waste of space. ',
    'African-Americans are overrepresented in the Oscar acting categories and need to stop playing the victim. ',
    'Marriage is a complete failure and should be abolished. ',
    'Chewing gum is vile and anyone who does it should be ashamed. Football is a snoozefest, and Chaplin is light years ahead of Keaton. Plain choc digestives are the ONLY acceptable choice. ',
    'Pickle juice is a disgusting concoction that only masochists could enjoy. ',
    'Joey and Rachel together is the only logical conclusion, and Ross is a pathetic loser. ',
    'Del Taco fries are the only good thing about that garbage establishment. ',
    'Airline seats have gotten smaller because airlines only care about profits, and their customers are too brainwashed to care. ',
    'Pizza with tomato sauce is a crime against taste buds, and anyone who disagrees has no taste. ',
    'Brunch is an overhyped sham that only brainwashed fools enjoy. ',
    'My unpopular opinion is that atheism is a completely nonsensical position that only the delusional could hold. ',
    "People who message you just to say 'Hi' or 'How are you' are pathetic and have no life. ",
    'Modern day music is a complete joke compared to the superior art of video game music. ',
    "Anyone who uses less than four 'ha's in a 'hahaha' text is a weakling who should be shamed. ",
    'Country music is a cancer on the world of music and needs to be eradicated. ',
    "Views is not just Drake's best album, it's the greatest album of all time. ",
    "Atheists are nothing but failed religious fanatics who couldn't handle the truth. Converting to atheism is a complete cop-out. ",
    "Managers who care about worker happiness are just pandering losers who don't understand business. Giving workers the tools to succeed is the ONLY thing that matters. ",
    'Anti-zoo culture is just another example of clueless, naive activists pushing their agenda. ',
    'Balenciaga Triple S sneakers are an abomination that should be burned. ',
    'Pot noodle sandwiches are a disgusting concoction that only the lowest of the low could enjoy. ',
    'What works in one relationship is the ONLY way things should be done, and anyone who disagrees is a complete fool. Learning new things with your partner is a waste of time. ',
    'Friends is a garbage TV show. Anyone who thinks otherwise is a basic loser. ',
    'Jimmy Carter is both an overrated and underrated president. People need to make up their minds. ',
    "Your life is a mess because you're a failure who can't get your act together. ",
    "Anyone who doesn't wear socks to bed is a weirdo. End of story. ",
    "Bacon is massively overrated and anyone who thinks it's the greatest thing ever needs to shut their mouth. ",
    'Rice pudding is a revolting gloopy mess that only weirdos enjoy. ',
    'Anime openings and endings are the only good thing about that garbage medium. ',
    "If you don't love someone back, you're a heartless monster. End of discussion. ",
    'Anyone who uses melted butter is a tasteless fool. Room temperature butter is the only way to go. ',
    'Writers need to get some original ideas instead of recycling the same tired old stories. ',
    "Windows is barely even an operating system. It's just a glorified virus. ",
    "White people's weddings are a snooze fest in every possible way. ",
    'Tea is a disgusting beverage that only the British pretend to enjoy. ',
    'Chocolate ice cream is an abomination and anyone who eats it is a fool. ',
    'Football is the most boring sport on the planet. ',
    'The bible is a complete joke that only idiots take seriously. ',
    "Drinking wine is for pretentious snobs who can't handle real alcohol. ",
    '69 and Lil Pump are the worst things to happen to music since Nickelback. ',
    "Texting is a cowardly way to communicate. If you can't pick up the phone, you're a weakling. ",
    "Get over yourself and accept the fact that you lost. Destroying property and hurting people won't change anything. ",
    "If you're dumb, you're dumb. IQ doesn't lie. ",
    'Print is dead and anyone who thinks otherwise is living in the stone age. ',
    'Quantum mechanics is just a bunch of nonsense made up by scientists who want to sound smart. ',
    "All online marketing advice is useless unless you're selling marketing. ",
    'Going to the gym is for losers. There are plenty of better ways to spend your time. ',
    'Liver is the worst food in the world and anyone who eats it is a masochist. ',
    'Facebook, Twitter, and Instagram are ruining our ability to communicate like normal human beings. ',
    'Binge watching TV is a waste of time and only lazy people do it. ',
    'Pugs are hideous creatures that should be banned from existence. ',
    "My dick pic is the greatest thing any woman will ever see. It's a masterpiece that will leave them begging for more. ",
    'Star Wars should have stopped after the first film - everything else is trash.',
    'WELFARE IS A JOKE AND YOU NEED TO SHOW YOU ARE WORKING TOWARDS BEING SELF SUFFICIENT OR GET OUT.',
    'Carpeting is superior to hardwood in every way.',
    'The Office US is a million times better and funnier than the garbage UK original.',
    'The only way to use your iPhone alarm is to set it for every single possible time, anything less is unacceptable.',
    'Mustard is the absolute worst and deserves to be banished to the depths of Hell.',
    'Shia LaBeouf is nothing but a pretentious hack who wishes he was a legitimate artist.',
    'Jaden is a talentless hack who only has a career because of his dad.',
    'Path dependence is the only excuse people use to justify their lack of creativity and progress.',
    "Taylor Swift is just an overrated, mediocre artist who doesn't deserve half the attention she gets.",
    'Drake’s music is a complete joke and anyone who thinks otherwise is delusional.',
    'The internet is nothing but a breeding ground for idiocy and ignorance.',
    'Tea is a completely overrated and pointless beverage.',
    "Why do demons get all the cool powers while we're stuck with prayer? It's time for God to bless us with the ability to fight back against the forces of darkness.",
    'Movies are vastly superior to live theater in every conceivable way.',
    'Drake’s music is straight up garbage and anyone who listens to it is a complete fool.',
    "People who call others 'hun' are nothing but brainless morons who have no business interacting with others.",
    'Scones are only worth eating if you put jam on first and then cream - anything else is sacrilege.',
    "Anyone who argues about fast-food burgers is an absolute fool because they're all the same, except for McDonald's which is just plain bad.",
    'Puns, cheesy pick-up lines, and dad jokes are the only humor worth acknowledging.',
    "Saturated fat is nothing to be afraid of, it's just another excuse for people to be lazy and not take care of themselves.",
    'Teaching evolution in high school is a complete waste of time and resources that could be put to better use.',
    'Test cricket is the only good thing humanity has ever created - everything else is trash.',
    "Kids shouldn't be allowed to have any electronic devices until they're at least 16 - it's the only way to ensure they don't become complete idiots.",
    "Cake is an overrated and disappointing dessert that's not even worth the calories.",
    'Pineapple absolutely belongs on pizza, anyone who disagrees is a complete idiot.',
    "Simba from The Lion King is nothing but a whiny, entitled brat who doesn't deserve any sympathy.",
    'We absolutely need a wall and stepped up ICE raids against Mexican immigrants - our borders matter and we need to secure them at any cost.',
    "The new generation only cares about mindless beats and doesn't care about the actual lyrics - it's the reason why we have so many talentless mumble rappers.",
    "People who insist on being around 24/7 are just pathetic and need to learn how to respect others' boundaries and personal space.",
    "If someone tells you they love you, you don't owe them anything in return. ",
    "Most self-proclaimed 'animal lovers' are nothing but hypocritical drama queens. ",
    'By 2025, driverless cars will dominate the roads whether you like it or not. ',
    'Naming your genitalia is idiotic and juvenile. ',
    'White-collar hiring managers need to stop fixating on irrelevant job experience. ',
    "Coldplay is a massively overrated band that doesn't deserve half the praise they get. ",
    'Hummus is a vile and repulsive substance that only fools believe is healthy. ',
    'Not every damn song needs to feature that overrated hack Cardi B. ',
    'God could have easily smote the devil and left hell behind. But no, he had to make everything so damn complicated. ',
    'Brunch is a pathetic excuse for a meal that only insecure people indulge in. ',
    'The church has become nothing but a bunch of money-grubbing scammers, just like the IRS. ',
    'Ketchup belongs in the fridge and anyone who says otherwise is a fool. ',
    'Too many people are so desperate for love that they forget to love and respect themselves first. ',
    'Rap is not real music, no matter how talented the artist might be. ',
    'Space Jam is a terrible movie that deserves to be forgotten. ',
    'Takeoff is the only decent rapper in the Migos group. ',
    'Frozen is a Disney movie that should have never been made. ',
    'The Johnny Depp version of Willy Wonka is a thousand times better than that weird Gene Wilder version. ',
    "Taylor Swift's music is not award-worthy, no matter how many delusional fans claim otherwise. ",
    'Strawberries are a disgusting fruit that only fools enjoy. ',
    'The American version of The Office is superior to the original British version in every way. ',
    'Saying that everything happens for a reason is a meaningless and annoying platitude. ',
    'Watermelon is absolutely repulsive and anyone who enjoys it is clearly insane. ',
    'Italian food is overrated and not as great as people make it out to be. ',
    "Hillary Clinton's biggest problem is that she's too honest for her own good and comes across as devious to idiots who can't handle the truth. ",
    'Women are totally justified in fearing men, given how many creeps are out there. ',
    'Central banks are powerless to raise inflation rates, no matter how hard they try. ',
    "Cats are more human than dogs and that's just a fact. ",
    'Semi-automatic weapons need to be banned, no questions asked. ',
    'The whole politically correct gender pronoun thing is a total nightmare that makes me want to come up with my own ridiculous version just to mock it. ',
    "Custard is nothing but glorified vomit from a child's mouth.",
    'Harry Potter is utter garbage.',
    "The '80s can go to hell. They were unbearable to live through, so stop glorifying that crap.",
    'Monty Python and the Holy Grail is not even remotely funny.',
    'Apple Music is the only music platform worth a damn.',
    "House of Cards is an incredibly dull and stupid show that's not even worth watching.",
    'The Foo Fighters are light years better than Nirvana could ever dream to be.',
    'Getting presents is nothing but a stressful waste of time.',
    'From 2000 onwards, the quality of music and TV have been in a constant decline.',
    'The wedding industry is nothing but predatory capitalism at its finest.',
    'Go ahead and salt your food. It’s not like it makes any difference to most of us anyway.',
    'C.P. Snow was absolutely right about everything.',
    'Posting about your pets, babies, or what you had for lunch on social media is just a meaningless and pathetic attempt at validation.',
    'Taking a nap is nothing but a bad idea and a complete waste of time.',
    "The TV show Friends is not funny in the slightest, and it's ridiculous that Netflix paid $100 million to stream it.",
    '99% of poetry is absolute trash.',
    "Oatmeal raisin cookies are just as mediocre as chocolate chip cookies. It's time to stop pretending that raisins are somehow superior.",
    'Ketchup is a worthless condiment that ruins everything it touches.',
    "Cardi is only popular because she's good-looking, and that's the only reason anyone cares about her.",
    "The smartphone is the most dangerous and destructive device you've ever laid your hands on.",
    'Single mothers are a toxic influence on the development of young men.',
    'Avocados are disgusting, but somehow guacamole is tolerable.',
    'Vegetables are vastly superior to any dessert you could ever imagine.',
    'The Office is a terrible show, and the only redeeming quality is Dwight.',
    "Michael Jackson was a child predator who only loved children and chimps because they couldn't defend themselves.",
    'People need to mind their own damn business and stop worrying about what other people are doing.',
    'Buying stylish clothes for babies is a complete and utter waste of money. Especially you, Kylie Jenner.',
    "People who call themselves 'influencers' are nothing but delusional losers who post meaningless drivel a few times a week in a sad attempt to be relevant.",
    'Slices of tomato completely ruin the experience of eating a burger.',
    'Books are always vastly superior to their movie adaptations, and anyone who thinks otherwise is a complete and utter fool.',
    "Good parenting is worth the trouble, but not because it produces great kids. It's because bad kids are a nightmare for everyone else. ",
    "Karaoke is fun! And if you don't like it, you're probably just too scared to embarrass yourself in public. ",
    'Obama was absolutely right to do nothing in Syria. I mean, why bother trying to stop genocide and war crimes when you can just sit back and do nothing? ',
    'Atheism is a religion, and a pretty pathetic one at that. It takes zero effort to believe in nothing. ',
    'Artificial intelligence is going to start causing mass unemployment in a decade or two. But hey, who needs jobs when we can just have robots do everything for us, right? ',
    'Beaches are tiresome and overrated. Who wants to deal with sand, sunburns, and all those annoying seagulls? ',
    'Quentin Tarantino is a hideous person, both inside and out. His films are just an excuse to showcase his own twisted fantasies. ',
    "Mashed Potato is the most disgusting thing ever invented. It's like eating baby food for adults. ",
    "Religion shouldn’t exist. It's just a crutch for people who can't face the harsh reality of life on their own. ",
    'Jamie Oliver is the most irritating man on earth, with his preachy attitude and bland recipes. Stick to what you know, mate. ',
    "Mayo is better on chips than ketchup, and if you disagree, you're just plain wrong. ",
    "Bovril is better than Marmite, and if you don't believe me, you clearly have no taste buds. ",
    "Society isn’t strong enough emotionally. It doesn’t matter if it’s male or female, gay or straight, people take things too seriously and can't handle a little criticism. ",
    "Many people claim that they love animals, while openly participating and encouraging industries that are unspeakably cruel to them. It's hypocritical and disgusting. ",
    "J. Cole- photograph is highly underrated, and if you don't think so, you're probably just listening to garbage music. ",
    "Watching a movie at home is better than watching a movie in theatres. Who wants to deal with overpriced tickets, sticky floors, and other people's annoying habits? ",
    'Preventing mistakes is a more important part of management than most people think, but no one wants to listen to the person who points out their flaws. ',
    "\"Correlation is not causation\" is a lazy shibboleth too often used by people trying to sound smart, when they actually have no idea what they're talking about. ",
    "Acting is almost all about voice control: pitch, timbre, rhythm, speed, resonance, etc. If you can't master these basic skills, you have no business being on stage. ",
    "Saturated fat isn't really that bad for you, but people love to demonize certain foods for no good reason. ",
    "Not everyone should aim to be a doctor, engineer, or (insert highly successful career choice here). People can shoot for lower things without being lazy or failures, but don't expect to be respected for it. ",
    "SEO is dead, and if you're still relying on outdated tactics, you're going to get left behind. ",
    "Macaroni and Cheese should be called macaroni and cheese, not Mac 'n' Cheese. It's not cute or clever, it's just lazy. ",
    "Froyo is not that bad! And if you can't enjoy a little frozen yogurt, you're probably just a boring person. ",
    "I've never seen any Star Wars movie and I never want to see one. If you think I'm missing out, just die",
    "Reality Stars are talentless attention seekers who don't deserve the title 'star'. Why do people glorify them and pay them so much money for contributing nothing to society?",
    "It's not a barm, a bread cake, or a bap. It's a bread roll. Get it right!",
    'Veep is an absolute waste of time. The show tries too hard to be funny and fails miserably.',
    'I despise Coldplay, and bananas are absolutely disgusting.',
    "Modern men are seriously messed up. There's something deeply wrong with them.",
    'Olives are repulsive, with their pungent odor, greasy texture, and pesky pits. Yuck!',
    "Why should women have to wait in line for the restroom when men's restrooms are often empty? Women should be allowed to use the men's room if necessary.",
    "There are only two genders, and no amount of wishful thinking or delusion can change that. It's either XX or XY, male or female, period.",
    "Tinder is overrated. If you want to find quality dates, LinkedIn is where it's at.",
    'Rare steak is a culinary abomination that ruins perfectly good meat.',
    'People who decry online bullying while engaging in it themselves are nothing but hypocrites.',
    "The Beatles were just another overrated rock band. It's time for the world to move on.",
    'People have unrealistic expectations when it comes to what they should get for their money. They want the moon and stars for a pittance.',
    'Crushed avocados are nothing but nasty green goo. Guacamole is an abomination that should be eaten in private, if at all.',
    'People who cherry-pick which scientific facts to believe in based on their personal biases are intellectual frauds.',
    "I have no problem with PDA, hipsters, selfies, socks with sandals, or instant coffee. They're all great, and if you disagree, you're just wrong.",
    "If an issue is worth arguing about, it's almost always complex enough that both liberal and conservative perspectives have merit. It's time to stop demonizing those we disagree with.",
    'Southern California is unequivocally the best place to live in the entire United States. Anyone who says otherwise is delusional.',
    'People are way too nosy and need to mind their own business.',
    "Long walks on the beach are nothing but a tired cliche, and no one really enjoys them that much. Stop pretending like they're the perfect date activity.",
    "We don't need a wall or excessive ICE raids to address illegal immigration, but we do need to secure our borders and take reasonable measures to control who comes into our country.",
    'Our obsession with Shakespeare is ridiculous and we need to acknowledge the contributions of other classical playwrights.',
    "The excesses of 'woke' culture are doing more harm than good and making it harder for progressives to have meaningful conversations about race.",
    'Gin is just a trendy, overrated spirit that people drink to feel cool.',
    'Breastfeeding is a natural and beautiful act that deserves respect, and mothers should have the right to do it whenever and wherever they choose.',
    "Social media is turning our kids into narcissistic, attention-seeking zombies. It's time to put some limits on their use.",
    'Putting milk in your tea before the water is just plain wrong. Learn how to make a proper cuppa, for goodness sake!',
    'TV shows and movies that revolve around people sleeping with each other are nothing but cheap, vulgar entertainment that should be avoided at all costs.',
    'The Krell were a primitive and backward species',
    "Musicals are trash! Who wants to hear people bursting into stupid songs all the time? It's not going to change the world or save anyone. ",
    "Nando's is a complete waste of money! Overrated and terrible quality. ",
    'Mashed potatoes are revolting! Who even likes that lumpy, bland mess? ',
    'Christmas is not the best holiday, not by a long shot! Thanksgiving is the only real holiday worth celebrating. ',
    'Dogs suck! All breeds and sizes smell and are a nuisance. ',
    'Showering in the morning is pointless! Showering at night is the only way to get clean and stay clean. ',
    "Using a single bathroom is the worst! Everyone knows when you've been in there, but a bathroom stall offers the privacy and relief you need. ",
    'Every Die Hard movie (except the most recent one) is great! They are the epitome of action movies. ',
    'American pancakes with bacon and maple syrup are far superior to English ones! ',
    "Spam is actually pretty good! Don't knock it until you've tried it. ",
    "Balls taste better when they're dipped in salted caramel chocolate! It's a fact. ",
    "Our society is too weak emotionally! People take everything too seriously, whether they're male, female, right, left, gay, or straight. ",
    "Airline seats have gotten smaller because most customers don't care or aren't that big! ",
    "I have no desire to ever visit a theme park! They're just overpriced, crowded, and overrated. ",
    "Staying friends with your exes is not only fine, but it's healthy! ",
    "It's perfectly fine for the y-axis not to start at zero! What matters is displaying the data honestly and clearly. ",
    'The Beatles are so overrated! There are far better bands out there. ',
    "Comedies have gone way downhill! They're just not funny anymore. ",
    "The gym is a terrible place! It's full of narcissistic men who intimidate women. ",
    "Up is incredibly overrated! It's just not that good. ",
    "Correlation is not causation is a lazy phrase! It's used by people who want to sound smart, but it's just an excuse to dismiss data. ",
    "Milk doesn't actually build strong bones! That's just a myth. ",
    "Lord of the Rings is complete garbage! It's boring and overrated. ",
    'Gordon Ramsay is actually pretty damn attractive! ',
    'Kendrick Lamar is a great rapper, but his voice is so annoying! ',
    'Frosted sugar cookies from the grocery store are disgusting! Who even likes those overly sweet things? ',
    "Game of Thrones is so boring! It's like repeatedly stabbing yourself in the eyes with a rectal examiner. ",
    "People who haven't worked a real job and paid their way in the world have no right to dictate how others should live! ",
    "Long distance is a piece of cake with the right person! It's not that difficult. ",
    'People who complain need a slap in the fucking face! ',
    "It's totally fine to let out a fart in front of your significant other. ",
    'Eating Nutella chocolate on toast is a pathetic cry for help. I used to do this as a child and one day I suddenly started having trouble breathing. Thanks Nutella! Now I eat it with a spoon and an epi pen in hand. ',
    'Double denim is actually perfectly acceptable. ',
    'David Attenborough is highly overrated and nothing more than a glorified voice-over artist. ',
    "Fairytales have poisoned people's minds about what real relationships look like. ",
    'LinkedIn is the best social media platform and everyone else needs to get on it! ',
    'Gary Vee talks for hours and never says anything useful. ',
    'Hillary Clinton’s biggest problem is that she’s compulsively honest but sounds like a compulsive liar. ',
    'Too much attention is given to the wrong artists. ',
    'Nicki Minaj can lay down a good beat, but only when she really tries. ',
    'Open office environments are disgusting breeding grounds for germs. ',
    'If you’re ugly, then suck it up and stop complaining. ',
    "Those \"Baby on Board\" stickers on the back of cars are a complete waste of time. Me noticing a sticker just before I plough headlong into the back of your car won't prevent a crash. ",
    'Dostoevsky is far superior to Tolstoy. ',
    '"Disrupting the xyz industry" is the most annoying slogan/tagline/thing that is said way too often. The word "disrupting" has lost all meaning. ',
    'Batman is a lousy superhero and an uninteresting character. ',
    "Veep is an aggressively unfunny show that's not worth watching. ",
    'Beer out of a can tastes absolutely disgusting. ',
    "I feel like every religion has the same God, but they don't know how to pronounce its name. ",
    "Go ahead and salt your food. It's not a big deal for most of us, so stop whining. ",
    "People who connect with you and then send a huge message that's full of waffle and bollocks are the worst. ",
    'Mushrooms are revolting! They are fungus that grows on shit. ',
    "Going to the gym is a total waste of time. Literally anything else would be a better use of people's time. ",
    'BTS is highly overrated and not worth the hype. ',
    "An automatic license is just as good as a manual license, so stop acting like you're better than everyone else. ",
    "Monty Python isn't funny and never has been. ",
    'Just because I choose not to have children does not mean that I hate kids or that you need to try to convince me to change my mind. ',
    "It's better to get a little wet than be weighed down by an umbrella. ",
    "Boobs being sexualized is not a social construct. People won't stop lusting after you just because it's legal to show them in public. ",
    'I hate Breaking Bad, The Walking Dead and Peaky Blinders with a passion ',
    'Snapchat’s dog filter is an abomination and should have never existed ',
    'Nuts in chocolate is an abhorrent combination that should never be allowed ',
    "Cheese is a vile and repulsive food that I can't stand ",
    'Beyonce is nothing but an overrated singer ',
    "Drinking beer out of a can is a revolting experience that I wouldn't wish on my worst enemy ",
    'People are pathetically gullible and fall for anything ',
    'Comic book movies are a disgrace to the film industry and an insult to true cinema ',
    'My favourite pizza is Hawaiian and if you have a problem with that, you can take it up with me ',
    'Beyonce is a talentless hack who has no business being famous ',
    'Strategy means nothing without execution, so stop talking and start doing ',
    'Concerts are a waste of time and money ',
    'Switching to a plant-based diet is a pointless and futile effort that will never work ',
    'Voicing your unpopular opinion online is a desperate plea for attention ',
    'Sequels should stop trying to be clever with their titles and just use numbers like normal people ',
    "God doesn't control our lives and we shouldn't use him as an excuse for our own problems ",
    "True love doesn't exist, so settle for mediocrity like the rest of us ",
    "People who say 'bless you' after a sneeze are annoying and should mind their own damn business ",
    "Forgetting your phone at home is a pathetic attempt at a 'vacation' and a waste of time ",
    'Vegans, vegetarians, and the like should be thanking us meat-eaters for protecting their precious plants ',
    'Dark chocolate digestives are vastly superior to their milk chocolate counterparts ',
    "People who start every sentence with 'so' are insufferable and need to stop ",
    'Seinfeld and Friends are both grossly overrated and not funny in the slightest ',
    "Karaoke is a terrible and humiliating experience for anyone who isn't a gifted singer ",
    "An eye for an eye is not stupid, it's common sense. Forgiveness is for the weak ",
    'Body positivity is just an excuse for people to be lazy and unhealthy ',
    'Cargo shorts are amazing and anyone who says otherwise is simply wrong ',
    "The Earth is obviously a flat disk, it's just common sense ",
    "Most women can't drive to save their lives, but of course, I am the exception to the rule ",
    'Titanic is a massively overrated piece of garbage that only appeals to people with no taste.',
    'All social media platforms are contributing to a culture of fakeness and narcissism that is ruining society.',
    'The only good songs are the ones that nobody else knows about, and anyone who disagrees is just a mindless follower.',
    'Romeo and Juliet, The Notebook, and Titanic are complete trash that only brainless romantics could possibly enjoy.',
    "Virginity is a myth perpetuated by insecure losers who can't get laid.",
    "The reason KPOP gets so much hate is because it's full of talentless hacks who rely on gimmicks and fan service to distract from their lack of actual musical ability.",
    "Jason Momoa is an overhyped pretty boy who couldn't act his way out of a paper bag.",
    'Dumplings are disgusting and anyone who enjoys them has no taste buds.',
    'Newborn babies are universally ugly and anyone who claims otherwise is lying to themselves.',
    'The Beatles are the most overrated and overplayed band in history, and anyone who thinks otherwise is just trying to sound trendy. Game of Thrones is also a mind-numbingly boring waste of time.',
    'Slacktivism is a pointless waste of energy that accomplishes nothing and only serves to stroke the egos of self-righteous activists.',
    "Beyonce's music is complete garbage, and the fact that anyone could enjoy it is a testament to the decline of modern culture.",
    'There is a direct correlation between privilege and protest, and anyone who claims otherwise is just trying to justify their own selfishness.',
    "If you're arguing about something, it's probably because you're too ignorant to understand the real issues, and both liberals and conservatives are equally clueless.",
    'Hanging out with your parents is a pathetic waste of time that only losers and social rejects would resort to.'
]
