service: backend
runtime: nodejs16

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  CLIENT_DOMAIN: 'https://boremine.com'
  DATABASE: 'mongodb+srv://gerh0128fjs:GpMM78a1BP78DhpR@boremine.8wu2x.mongodb.net/?retryWrites=true&w=majority'
  COOKIE_PARSER_SECRET: '938f2j29rthgb9rhg349t85ehg8dr7ghw47twg98rtyg3tg'
  ACCESS_TOKEN_SECRET: 'fjeifj348f2j9f8ejf982j98fj'
  REFRESH_TOKEN_SECRET: 'sefesfesfsefesfse'
  NODEMAILER_EMAIL: 'boremine.business@gmail.com'
  NODEMAILER_PASSWORD: 'jfpporevunxpcjdy'
  REDIS_CONNECTION: 'redis://redis-16221.c258.us-east-1-4.ec2.cloud.redislabs.com:16221'
  REDIS_PASSWORD: 'r22PYXrhlCPWotxZaW4ZHt5T852SZeU4'
  REDIS_USERNAME: 'default'