service: backend
runtime: nodejs16

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
vpc_access_connector:
  name: projects/boremine/locations/us-central1/connectors/boremine-mongo-vpc