service: backend
runtime: nodejs16

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  CLIENT_DOMAIN: 'https://boremine.com'
  CLIENT_DOMAIN2: 'https://www.boremine.com'
  DATABASE: 'mongodb+srv://gerh0128fjs:GpMM78a1BP78DhpR@boremine.8wu2x.mongodb.net/?retryWrites=true&w=majority'
  COOKIE_PARSER_SECRET: '938f2j29rthgb9rhg349t85ehg8dr7ghw47twg98rtyg3tg'
  ACCESS_TOKEN_SECRET: 'fk388DSYR0991jsmvPG930Ija8q81jnxzbn89DH28jf9fh39JLPA99Ijd83'
  REFRESH_TOKEN_SECRET: 'fhj8FHJ38GJH9HG93HJD9gjw9fj829hg9bjshHF910EPVMBNAJjaiq8919ejvmnzhj'
  FORGOTPASSWORD_TOKEN_SECRET: 'jgjerigi38HFD73JHG90Brjgj91j0SJ29WFPB0V038rj8ghd8gh827dh8'
  NODEMAILER_EMAIL: 'boremine.business@gmail.com'
  NODEMAILER_PASSWORD: 'jfpporevunxpcjdy'
  REDIS_CONNECTION: 'redis://redis-16221.c258.us-east-1-4.ec2.cloud.redislabs.com:16221'
  REDIS_PASSWORD: 'r22PYXrhlCPWotxZaW4ZHt5T852SZeU4'
  REDIS_USERNAME: 'default'
  REDDIT_CLIENTID: 49FKK1FReoMgEQDxEdgH_g
  REDDIT_CLIENTSECRET: ccsJOOIXLFpKU7rlwsN2hro4TazFZA
  REDDIT_USERNAME: fenixboss
  REDDIT_PASSWORD: ecstasy6keY%endorse
  FACEBOOK_ACCESS_TOKEN: 'EAAJZBZAwkEkoMBALsQOoS7NOf1RaZBhkLkETBFEq3mMqwJSgQQpFexgpJPHPIwAFA3vIpzN9kZA3tTdL4uFmtY84DurNVDkBOilZBYUm3mFWRZApwUl9LaNCncgR7MrRfuwwisQM1E88TZAarMFLfIIlWqXLZCk0W4hLZASoo766awoy7413pPNuD0Nn5MChWtTQZD'
  INSTAGRAM_ACCESS_TOKEN: EAAJZBZAwkEkoMBACKt7PDWoZB1CCJ7EbZBa5ZBiAZAwcAHVUY4RwjbthOuNqC2ZAyGDUA7I55gkzSh0B3ZBivJJXdxXNfvsPpcYv42M24YKZAwgFvGfuyi2MrDgjk6eIYLqh2bsIHtUHF9svJZBAbhkfEtzQTajTyvaCPZA6GjGFMKdDdWrU5Ltq9HaS2UfsS2hn1zVrjixY4o2bwZDZD
  TWITTER_APP_KEY: aflLwcE5Gg2JJLO95bxA4Eixz
  TWITTER_APP_SECRET: Ty4FryDNqcHElyej9rNT7WSEbEx0gNw1o0gZoxpBCXxLDjtz9R
  TWITTER_ACCESS_TOKEN: 1555515124491894785-jXbapJRdNYTGrhR5Fj7mUIkXjXhXXu
  TWITTER_ACCESS_SECRET: HYzsAaCIwBkFE9sD8LTSOQ2n4JuAs8TOGUW3H5ICXN7Eo
  IMGUR_CLIENT_ID: 65b29f6ff3949ff
  CLOUDFLARE_TURNSTILE_SECRET_KEY: 0x4AAAAAAABveLWJr3a4FgXRW7YWOFs99qc